# ~/.config/starship.toml

# Inserts a blank line between shell prompts
add_newline = true

# Change the default prompt format
format = """\
[╭╴](238)$os$username\
$all[╰─](238)$character"""

# Change the default prompt characters
[character]
success_symbol = "[](238)"
error_symbol = "[](238)"

# Shows OS Logo
[os]
format = '[$symbol](bold white) '
disabled = false

[os.symbol]
Windows = ' '
Ubuntu = ' '
Arch = ' '
Macos = ' '

# Shows the username
[username]
style_user = "white bold"
style_root = "black bold"
format = "[$user]($style) "
disabled = true  # disable in powershell
show_always = false

[directory]
truncation_length = 2
truncation_symbol = "…/"
home_symbol = "  ~"
read_only_style = "197"
read_only = "  "
format = " at [$path]($style)[$read_only]($read_only_style) "

[fill]
symbol = "_"

[git_branch]
symbol = " "
format = "on [$symbol$branch]($style) "
truncation_length = 5
truncation_symbol = "…/"
style = "bold green"

[git_status]
format = '[\($all_status$ahead_behind\)]($style) '
style = "bold green"
conflicted = " "
up_to_date = " "
untracked = " "
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
stashed = " "
modified = " "
staged = '[  \($count\)](green)'
renamed = "󰑕 "
deleted = " "

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[git_commit]
commit_hash_length = 4
format = '[\($hash$tag\)]($style) '
style = "bold-green"
tag_symbol = '  '
disabled = false

[nodejs]
format = "via [  $version](bold green) "
disabled = true

[terraform]
format = "via [ terraform $version]($style) 壟 [$workspace]($style) "

[vagrant]
format = "via [ vagrant $version]($style) "

[docker_context]
format = "via [ $context](bold blue) "

[helm]
format = "via [ $version](bold purple) "

[python]
symbol = " "
python_binary = "python3"

[ruby]
format = "via [ $version]($style) "

[kubernetes]
format = 'on [󱃾 $context\($namespace\)](bold purple) '
disabled = false
[kubernetes.context_aliases]
"clcreative-k8s-staging" = "cl-k8s-staging"
"clcreative-k8s-production" = "cl-k8s-prod"